### ISSUE TITLE
Getting Invalid session no matter what i do

### ISSUE THREAD

**Issue by TerikKek** [3arthqu4ke/PingBypass#12]
restarted pc 
restarted both servers
uninstalled minecraft on the server 
relogged into the accounts on the server and on the pc
dont rlly know what to do now.

**Comment by TerikKek** [comment]
error msg was on the server

**Comment by TerikKek** [comment]
mods used:future, phobos 1.5.4, optifine.

**Comment by 3arthqu4ke** [comment]
Are you using the same account on your pc and pingbypass?

**Comment by TerikKek** [comment]
yes

**Comment by 3arthqu4ke** [comment]
You need to use different ones.

**Comment by TerikKek** [comment]
k
