### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by redvx** [3arthqu4ke/PingBypass#14]
game crashing upon running
https://github.com/3arthqu4ke/PingBypass/files/5745371/crash-2020-12-27_14.48.49-client.txt) <--- crash log
could someone help me fix this?

**Comment by 3arthqu4ke** [comment]
Make sure that you use your actual internal IP and a port that is not being used.

**Comment by redvx** [comment]
im retarded how do i get this to work

**Comment by 3arthqu4ke** [comment]
What OS is your PingBypass VPS on?

**Comment by redvx** [comment]
vps? whats that?

**Comment by 3arthqu4ke** [comment]
PingBypass is supposed to run on a remote server. Theres no reason to try and run it on your own pc. So what OS does that server have?

**Comment by redvx** [comment]
idk
