### ISSUE TITLE
AutoCrystal improvments 

### ISSUE THREAD

**Issue by ghost** [3arthqu4ke/PingBypass#27]
-AutoSwitch would be a great feature for servers like 2b2t - elite anarchy
- AutoCrystal targets crystals placed by other players . this is really bad because they also will have the upperhand while pvping 
- AutoCrystal targets friends

**Comment by 3arthqu4ke** [comment]
-I don't see how that is bad since it calculates the damage that crystal will deal to you and the other player. It will only be blown up if it deals more damage to the other player than you.
-AutoCrystal shouldn't target friends, make sure to add them with the PingBypassClient.

**Comment by ghost** [comment]
-I mean in the sense of auto crystal speed , it makes other people's ca fast as well
