### ISSUE TITLE
how do i find ip and port and how should i type them in 

### ISSUE THREAD

**Issue by Socks4linqq** [3arthqu4ke/PingBypass#29]

**Comment by 3arthqu4ke** [comment]
You should find a file called Server.json in your minecraft directory if youve started the game once. In there you should have a line that looks like this:
"IServerIP": "127.0.0.0",
Replace the 127.0.0.0 with the internal IP of your VPS (should be provided by the host), and the port with the number of the port that you opened.

**Comment by jamesbond78** [comment]
what do i do if i connect with tcp connection?
