### ISSUE TITLE
How powerful a vps do you need

### ISSUE THREAD

**Issue by ghost** [3arthqu4ke/PingBypass#3]
How powerful a VPS do you recommend for this

**Comment by 3arthqu4ke** [comment]
Not very powerful. I personally used a Google Cloud Platform VM with 4GB RAM. Id say 3 GB allocated for Minecraft is the minimum and I recommend turning on the NoRender Option in the PingBypass module.

**Comment by 3arthqu4ke** [comment]
If you can get more obviously get more, I also used Optifine with it.
