### ISSUE TITLE
 org.lwjgl.LWJGLException: Pixel format not accelerated

### ISSUE THREAD

**Issue by IkegamiI** [3arthqu4ke/PingBypass#32]
Whenever I run minecraft forge 1.12.2 on the server it crashes and it gives the error  org.lwjgl.LWJGLException: Pixel format not accelerated.

**Comment by 3arthqu4ke** [comment]
I recommend using this: https://github.com/3arthqu4ke/HeadlessForge

**Comment by 3arthqu4ke** [comment]
Another thing you could try would be setting up a remote desktop and running the [monitorscript.sh](https://github.com/3arthqu4ke/PingBypass/blob/main/monitorscript.sh) before you start Minecraft.

**Comment by IkegamiI** [comment]
Hi yes headless forge worked.

**Comment by 3arthqu4ke** [comment]
Nice!
