### ISSUE TITLE
Spams in chat

### ISSUE THREAD

**Issue by fatchode** [3arthqu4ke/PingBypass#34]
Whenever I log into a server first you get an error message, then it starts to spam in chat. [](url)
![image](https://user-images.githubusercontent.com/78627860/114950375-e13dd500-9e20-11eb-9ae3-7db2b97dbfa5.png)
![image](https://user-images.githubusercontent.com/78627860/114950391-ea2ea680-9e20-11eb-9056-7d9a690dc33a.png)

**Comment by 3arthqu4ke** [comment]
Either you are not connected to the PingBypass in the first place, or you have some sort of Chat-Prefix module on.
