### ISSUE TITLE
![image](https://user-images.githubusercontent.com/72895337/114942483-391d1180-9e0a-11eb-81a5-1a6afc62715e.png)

### ISSUE THREAD

**Issue by italoaa** [3arthqu4ke/PingBypass#35]
![image](https://user-images.githubusercontent.com/72895337/114942483-391d1180-9e0a-11eb-81a5-1a6afc62715e.png)
this is my logs after using the headless forge. The file Server.json did no show up so I created it and filled it but it did not work.

this are some more logs before the last ones
![image](https://user-images.githubusercontent.com/72895337/114942818-b8124a00-9e0a-11eb-9ff8-ae72be0ad53e.png)

this is what it says 
![image](https://user-images.githubusercontent.com/72895337/114942999-f90a5e80-9e0a-11eb-95d8-8475e0136688.png)

_Originally posted by @italoaa in https://github.com/3arthqu4ke/PingBypass/issues/33#issuecomment-820751733_

**Comment by italoaa** [comment]
got it to finally work it needed a restart but now when entering a server it gets stuck in loading PingBypass
![image](https://user-images.githubusercontent.com/72895337/114958031-d0dd2880-9e27-11eb-9b08-096a5c5b9057.png)
is this normal?

**Comment by 3arthqu4ke** [comment]
I assume that you didn't use an [Accountmanager](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher)? Headlessforge doesn't support loging in by default. You most likely get disconnected for an invalid session. Use the click and gui commands to log in with that Accountmanager.


For the Server.json: make sure that you build from the latest commit, since that fixes the Server.json not being created. You can fill the Server.json with this:

```json
 {
"Bind": "NONE",
"IServerIP": "<internal ip of your vps>",
"Port": <port>,
"NoRender": false,
"Hidden": false,
"Enabled": false,
"Name": "PingBypass"
}
```

**Comment by italoaa** [comment]
would logging in through a vnc connection work?

**Comment by italoaa** [comment]
I just tried to use the account manager but when using the session command my Account is not displayed but a random player name.
![image](https://user-images.githubusercontent.com/72895337/115041005-aa56d600-9e97-11eb-9b62-77928b3bd61a.png)

**Comment by 3arthqu4ke** [comment]
In the main menu:
- gui command -> you are going to see that theres a button with id 20
- click 20, 
- gui command again, you see a button with id 0 (addacount),
- click 0,
- gui command again, you see theres 2 textfields.
- text 0 email of account
- y
- text 1 password
- y
- click 2 (add account)
- you are now in the previous gui
- click 1 (login)
- session

**Comment by italoaa** [comment]
Thank youuuuu worked perfectly

**Comment by 3arthqu4ke** [comment]
Nice!
