### ISSUE TITLE
How do i install the client?

### ISSUE THREAD

**Issue by 8-bad** [3arthqu4ke/PingBypass#42]
I'm sorry, im new to github so i'm not sure how i should install the client, because i dont see any releases or anything

**Comment by 3arthqu4ke** [comment]
You will need the Java Development Kit 8 or higher.
Go into the directory of the project where you find all the files (build.gradle etc.) and open the command line in that directory.
Enter `gradlew setupDecompWorkspace` and after it completed `gradlew build`. You'll find your jar under `build/libs/`. There might be 2 jars in there, take the bigger one.
