### ISSUE TITLE
Loading pb

### ISSUE THREAD

**Issue by iBikky** [3arthqu4ke/PingBypass#49]
When I join a server it just says loading pingbypass

**Comment by 3arthqu4ke** [comment]
What do the logs from the PingBypass say?

**Comment by 3arthqu4ke** [comment]
Since you are using HeadlessForge I assume that you dont use an account switcher and you are not logged in. Thats the most common reason for this error.

**Comment by iBikky** [comment]
when I use account switcher it crashes me

**Comment by 3arthqu4ke** [comment]
Cool, but how am I supposed to know what crashes you without a log.
