### ISSUE TITLE
Trying to use but no way to connect to the proxy 

### ISSUE THREAD

**Issue by dekrom** [3arthqu4ke/PingBypass#59]
![image](https://github.com/3arthqu4ke/pingbypass/assets/7980096/d8a3fa86-88f0-420f-8104-1d1595d23b45)

Is there any command to connect to the proxy?
Can you help me out using it?

**Comment by 3arthqu4ke** [comment]
Right now there is no PingBypass functionality, it is just a client base that I use to run [Phobot](https://github.com/3arthqu4ke/Phobot).

I have started to work on said [functionality](https://github.com/3arthqu4ke/pingbypass/tree/1.20.4/pb-server/src/main/java/me/earth/pingbypass/server/handlers), but I currently do not have the time to finish it.

`+` is the default prefix that you are looking for in that command screen.
If I finish the PingBypass functionality you would start the pb-server somehwere, then add it just like any other Multiplayer server in Minecrafts Multiplayer Menu.
