### ISSUE TITLE
CA Improvements and others

### ISSUE THREAD

**Issue by TerikKek** [3arthqu4ke/PingBypass#6]
CA is known to stop placing and breaking and requires either a reset of the config or toggling it on or off again.
CA could place faster but wouldnt needed
CA raytrace: wouldnt place/break through walls (for const)
CA strict rotations (for 2b2t and oldfag type servers)

some sort of explanation for some of the weirder settings
ie Breaktrace, Placetrace
exactly what multiplace does

chat notifier for module toggles
Autototem improvements (offhand fails regularly) adding crystal/gap mode 
a light-weight gui for easy configing

these are the problems i've found in the pingbypass everything else has been pretty smooth

**Comment by TerikKek** [comment]
for CA strict rotations this can also limit the speed of the placing in breaking (yes i know that break delay and place delay exist. but for a server like 0b i get kicked reapeadtly for sending too many break and place packets)

**Comment by 3arthqu4ke** [comment]
Im not sure if I can recreate the CA stopping placing and breaking, do you use Rotations?
I forgot that this client has no descriptions, I will add them sometime. 

-PlaceTrace: Wallrange for placing crystals,
-BreakTrace: Wallrange for breaking crystals,
-CombinedTrace: Wallrange for placing crystals too, but with the offset for breaking (minecraft mechanics). So essentially if you put Combined and BreakTrace on the same Value no crystals that lie outside BreakTrace Range will be placed.

Put PlaceTrace to 0 for const, Break and CombinedTrace should have similar values, idk if you can break through walls on const, so you might want to set those to 0 as well.

Good Suggestions.

**Comment by TerikKek** [comment]
also for the CA stopping placing it happens on cpvp.cc and on anarchy hvh i think it is a config error tho
ill look into it more

**Comment by notperry1** [comment]
doesn't happen to me

**Comment by TerikKek** [comment]
does for me, care to send me a config?

**Comment by TerikKek** [comment]
still happening shits ass

**Comment by TerikKek** [comment]
locks up on uscpvp.cc
