### ISSUE TITLE
what is instant and override 

### ISSUE THREAD

**Issue by cats-ui** [3arthqu4ke/PingBypass#7]
what is instant and override in ca settings

**Comment by 3arthqu4ke** [comment]
Instant was known as Predict before. It attacks the crystal in the moment the SpawnPacket for it arrives, which can save up to 50ms per crystal.

Override ignores the MaxSelfPlace and MaxSelfBreak Damage that the crystal will deal to you (still checks that that crystal doesn't kill you), if it can deal lethal damage to the target with it.
