### ISSUE TITLE
im trying setup pingbypass

### ISSUE THREAD

**Issue by cats-ui** [3arthqu4ke/PingBypass#8]
and i got this issue 
https://cdn.discordapp.com/attachments/781366955969347614/786800802479603712/unknown.png

**Comment by cats-ui** [comment]
also which remote dekstop u installed? cinnamon?

**Comment by cats-ui** [comment]
so 1.13-1.16 is working. 1.12 and 1.9 1.12.2 1.11 1.8 isnt working at all

**Comment by 3arthqu4ke** [comment]
I just commited a bash script that fixed XRandR crashes for me:
https://github.com/3arthqu4ke/PingBypass/blob/main/monitorscript.sh
Put that on your VM and run it before you start Minecraft. ( ./monitorscipt.sh )

**Comment by cats-ui** [comment]
> I just commited a bash script that fixed XRandR crashes for me:
> https://github.com/3arthqu4ke/PingBypass/blob/main/monitorscript.sh
> Put that on your VM and run it before you start Minecraft. ( ./monitorscipt.sh )

is this working with 2-4 people?

**Comment by 3arthqu4ke** [comment]
Eh not really, you should have one VM per person.

**Comment by cats-ui** [comment]
> Eh not really, you should have one VM per person.

so i got this error https://cdn.discordapp.com/attachments/781162044757377034/786970575734046730/unknown-21.png
what i should do?

**Comment by 3arthqu4ke** [comment]
sudo -s? Im not good with linux so google will help you better with that issue.
