### ISSUE TITLE
[BUG] idek kek

### ISSUE THREAD

**Issue by Madmegsox1** [3arthqu4ke/PingBypass#9]
![2020-12-13_20 52 22](https://user-images.githubusercontent.com/68086870/102023691-31c6f800-3d85-11eb-857b-c03353033fe5.png)

It does this every time I log in or enable ca or any modules, and the modules don't work.

**Comment by 3arthqu4ke** [comment]
Turn off any chat suffix mods.

**Comment by Madmegsox1** [comment]
LMAO based

**Comment by Madmegsox1** [comment]
thx
